language: java
jdk:
  - oraclejdk8
script:
  - find $HOME/.m2 -name "_remote.repositories" | xargs rm
  - mvn verify

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.m2/repository

# whitelist
branches:
  only:
    - master
